### PR TITLE
fix: Fix path mismatches on Windows

### LINKED ISSUE #2407: Unable to upload PDB files from Windows using sentry-cli
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Through Windows powershell, use sentry-cli version 2.41.1 to point at a folder, and upload its debug files. Make sure to have .pdb files inside.

### Expected Result

The included debug files are uploaded successfully.

### Actual Result

sentry-cli does not find the files in the folder, and does not upload them.

Pointing to a specific .pdb file within that folder instead uploads it successfully. Also, trying to upload the debug files of that same folder through macOS' terminal uploads the files successfully.

Debug logs and more information in [the shadow ticket](https://getsentry.atlassian.net/browse/FEEDBACK-2401?atlOrigin=eyJpIjoiZmQ2OWEwZTM4NTkwNDBkZjlhZTdiYjQwYzI3YjFiYmQiLCJwIjoiaiJ9).

### Product Area

Processing

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by BYK**
Attempts to fix https://github.com/getsentry/sentry-cli/issues/2413

### CODE REVIEW

File: src/utils/sourcemaps/inject.rs [hunk 1]
```diff
@@ -481,6 +494,41 @@ something else
 
     #[test]
     fn test_normalize_sourcemap_url() {
+        // TODO: Enable the following test and make it pass
+        // Linux allows having `\` in a file name but our path helpers,
+        // specifically `join_path` and `clean_path` from `symbolic::common`,
+        // do not use `std::path::MAIN_SEPARATOR` and instead tries to guess
+        // the path style by the existence of a `\` in the path. This is
+        // problematic because it can lead to incorrect path normalization.
```
Comment (loewenheim) [inline src/utils/sourcemaps/inject.rs:502]: Just to explain this a bit: the functions in `symbolic` work this way because they are not necessarily intended to be used on paths existing on the machine they're running on. Rather, they are used for paths stored in debug files and the like, which we want to combine and canonicalize. For this purpose they should work independently of the host system. For example, a path stored in a Windows debug file should be transformed and displayed the same regardless of whether you're using `symbolic` on Windows or Unix.

File: src/utils/sourcemaps/inject.rs [hunk 2]
```diff
@@ -481,6 +494,41 @@ something else
...
+        // assert_eq!(
+        //     normalize_sourcemap_url("/foo/ba\\r/baz.js", "baz.js.map"),
+        //     "/foo/ba\\r/baz.js.map"
+        // );
+
+        assert_eq!(
+            normalize_sourcemap_url(
+                &format!("foo{0}bar{0}baz.js", std::path::MAIN_SEPARATOR),
```
Comment (loewenheim) [inline src/utils/sourcemaps/inject.rs:510]: TIL about this syntax

**Review by loewenheim — APPROVED** [review]

**Review by lcian — APPROVED** [review]

File: src/utils/sourcemaps/inject.rs (hunk 1 above)
Comment (lcian) [reply src/utils/sourcemaps/inject.rs:502]: Overall I think we could also state that backslashes in Unix paths are not supported by `sentry-cli` and leave it at that, it should be extremely uncommon for backslashes to be present anyway.

File: src/utils/sourcemaps/inject.rs (hunk 2 above)
Comment (BYK) [reply src/utils/sourcemaps/inject.rs:510]: Me too. This is my first working Rust patch 😂
