### PR TITLE
fix(chunk): Fail with org not found on 404 to chunk endpoint

### LINKED ISSUE #2900: Assume `404` when getting `/chunk-upload` endpoint is due to non-existent org
In Sentry CLI 2.x, we have assumed that [404 errors when getting the chunk upload options](https://github.com/getsentry/sentry-cli/blob/78c4afb8cee9d433c2ac985a2cf1cf22816994ed/src/api/mod.rs#L958-L974) are due to the server not supporting chunked uploads. However, given that this endpoint has existed for quite some time, and given that Sentry CLI 3.x will only support servers that have this endpoint, in the 3.x release, we should assume a `404` error necessarily indicates that the organization does not exist, as this is the only possible cause of a `404` when using any recent Sentry version.

See also #2820 ([CLI-176](https://linear.app/getsentry/issue/CLI-176/non-existent-org-causes-chunk-upload-not-supported-error)).

### PR DESCRIPTION
**Pull request by szokeasaurusrex**
### Description
⚠️ **Breaking change:** Do not merge until ready to release in a major.

As Sentry CLI 3.0.0 will only support Sentry servers with chunk uploading support, we can now assume that 404 errors from the `/organizations/{org}/chunk-upload/` endpoint are due to the organization not existing, and not due to the chunk upload endpoint not existing.

### Issues
- Resolves #2900
- Resolves [CLI-211](https://linear.app/getsentry/issue/CLI-211/assume-404-when-getting-chunk-upload-endpoint-is-due-to-non-existent)

________

BREAKING CHANGE: Several subcommands no longer support Sentry servers which lack support for chunked uploads.

### CODE REVIEW

**Comment by szokeasaurusrex** [comment]
* **#2993** <a href="https://app.graphite.com/github/pr/getsentry/sentry-cli/2993?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2  dependent PRs ([#3022](https://github.com/getsentry/sentry-cli/pull/3022) <a href="https://app.graphite.com/github/pr/getsentry/sentry-cli/3022?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#3025](https://github.com/getsentry/sentry-cli/pull/3025) <a href="https://app.graphite.com/github/pr/getsentry/sentry-cli/3025?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2989** <a href="https://app.graphite.com/github/pr/getsentry/sentry-cli/2989?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#3005** <a href="https://app.graphite.com/github/pr/getsentry/sentry-cli/3005?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#3006** <a href="https://app.graphite.com/github/pr/getsentry/sentry-cli/3006?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#3004** <a href="https://app.graphite.com/github/pr/getsentry/sentry-cli/3004?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#3002** <a href="https://app.graphite.com/github/pr/getsentry/sentry-cli/3002?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2991** <a href="https://app.graphite.com/github/pr/getsentry/sentry-cli/2991?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2986** <a href="https://app.graphite.com/github/pr/getsentry/sentry-cli/2986?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2973** <a href="https://app.graphite.com/github/pr/getsentry/sentry-cli/2973?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2972** <a href="https://app.graphite.com/github/pr/getsentry/sentry-cli/2972?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2971** <a href="https://app.graphite.com/github/pr/getsentry/sentry-cli/2971?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2961** <a href="https://app.graphite.com/github/pr/getsentry/sentry-cli/2961?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2957** <a href="https://app.graphite.com/github/pr/getsentry/sentry-cli/2957?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2959** <a href="https://app.graphite.com/github/pr/getsentry/sentry-cli/2959?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2956** <a href="https://app.graphite.com/github/pr/getsentry/sentry-cli/2956?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2955** <a href="https://app.graphite.com/github/pr/getsentry/sentry-cli/2955?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2952** <a href="https://app.graphite.com/github/pr/getsentry/sentry-cli/2952?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2948** <a href="https://app.graphite.com/github/pr/getsentry/sentry-cli/2948?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2947** <a href="https://app.graphite.com/github/pr/getsentry/sentry-cli/2947?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2940** <a href="https://app.graphite.com/github/pr/getsentry/sentry-cli/2940?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2935** <a href="https://app.graphite.com/github/pr/getsentry/sentry-cli/2935?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2918** <a href="https://app.graphite.com/github/pr/getsentry/sentry-cli/2918?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2930** <a href="https://app.graphite.com/github/pr/getsentry/sentry-cli/2930?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/getsentry/sentry-cli/2930?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2876** <a href="https://app.graphite.com/github/pr/getsentry/sentry-cli/2876?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#3027** <a href="https://app.graphite.com/github/pr/getsentry/sentry-cli/3027?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: src/api/errors/api_error.rs [hunk 1]
```diff
@@ -63,6 +61,9 @@ impl ApiError {
         }
     }
 
+    // This method is currently only used in the macOS binary, there is no reason
```
Comment (runningcode) [inline src/api/errors/api_error.rs:64]: I'm confused by this comment, should it read "there is no reason to expose it on other platforms" ?

Comment (szokeasaurusrex) [reply src/api/errors/api_error.rs:64]: It should probably read "there is no reason not to expose it on other platforms"
