### PR TITLE
fix(sourcemaps): Avoid associating only sourcemap with all minified sources

### LINKED ISSUE #2438: Multiple source files can erroneously be associated with the same sourcemap
The function `collect_sourcemap_references` is supposed to associate sourcemaps with their corresponding minified source files. If the minified source file contains a URL pointing to the sourcemap, everything is clear, but otherwise there is some guesswork involved (e.g. if the minified source file is `foo.js` see if there is a sourcemap `foo.js.map`, and so on).

The function `guess_sourcemap_reference` which implements these heuristics contains this bit right at the start: https://github.com/getsentry/sentry-cli/blob/28d534d7a6d8d0a94b695796cf47c5bb8689aebb/src/utils/sourcemaps.rs#L114-L123

I.e. if there is exactly one sourcemap, it will be associated with every source file that doesn't have an explicit URL set! That's obviously not right. During injection this manifests as `sentry-cli` trying to inject the same sourcemap multiple times, and the result of the injection depending on which minified source file it encounters first.

Attached is a zip containing a folder with a few source files and a single sourcemap. Running injection on it produces the following result:
```
❯ sentry-cli sourcemaps inject --dry-run test
[…]
Source Map Debug ID Injection Report
  Modified: The following source files have been modified to have debug ids
    26feb2ad-831d-5f13-8772-bc09c6393c06 - test/bar.js
    26feb2ad-831d-5f13-8772-bc09c6393c06 - test/baz.js
    26feb2ad-831d-5f13-8772-bc09c6393c06 - test/foo.js
  Modified: The following sourcemap files have been modified to have debug ids
    26feb2ad-831d-5f13-8772-bc09c6393c06 - test/baz.js.map
  Ignored: The following sourcemap files already have debug ids
    26feb2ad-831d-5f13-8772-bc09c6393c06 - test/baz.js.map
    26feb2ad-831d-5f13-8772-bc09c6393c06 - test/baz.js.map
```
If we remove the offending bit of code from `guess_sourcemap_reference`, we instead get
```
Source Map Debug ID Injection Report
  Modified: The following source files have been modified to have debug ids
    e242ed3b-ffcc-5f27-9b7f-baf34ed72d08 - test/bar.js
    26feb2ad-831d-5f13-8772-bc09c6393c06 - test/baz.js
    f1d2d2f9-24e9-56ac-86fd-f7b36c94bcdf - test/foo.js
  Modified: The following sourcemap files have been modified to have debug ids
    26feb2ad-831d-5f13-8772-bc09c6393c06 - test/baz.js.map
```
which makes much more sense. Note that `baz.js` and `baz.js.map` have the same debug ID because they are associated, whereas `foo.js` and `bar.js` have different debug IDs because they aren't associated with `baz.js.map`.

ETA: Forgot to attach repro.

[test.zip](https://github.com/user-attachments/files/19466021/test.zip)

### PR DESCRIPTION
**Pull request by szokeasaurusrex**
Remove the branch from `guess_sourcemap_reference` which handles the case of there only being one sourcemap. If there are multiple minified souces, they would all (erroneously) end up associated with the same single sourcemap.

Also, since code for uploading bundles was relying on this branch (specifically when unpacking bundles), refactor so that we use the sourcemap which is passed to the command directly, rather thna "guessing" it.

Fixes https://github.com/getsentry/sentry-cli/issues/2438
Fixes https://github.com/getsentry/sentry-cli/issues/2503

### CODE REVIEW

**Review by szokeasaurusrex — COMMENTED** [review]
@loewenheim, when reviewing this change, please note that I split off some parts of #2438 into [separate issues](https://github.com/getsentry/sentry-cli/issues/2438#issuecomment-2758134658)

**Review by loewenheim — DISMISSED** [review]

**Comment by szokeasaurusrex** [comment]
@loewenheim I made some pretty significant changes to get the tests to pass here, so I'd appreciate a re-review

File: src/utils/sourcemaps.rs [hunk 1]
```diff
@@ -275,75 +263,28 @@ impl SourceMapProcessor {
...
-            self.sources.insert(url.clone(), source_file);
+            self.add_file_to_sources(SourceFile::from_release_file_match(&url, file));
             pb.inc(1);
         }
         pb.finish_with_duration("Analyzing");
     }
 
+    /// Adds a given source_file to sources, taking ownership of the source_file
+    /// but returning a reference to it.
+    fn add_file_to_sources(&mut self, source_file: SourceFile) -> &SourceFile {
```
Comment (loewenheim) [inline src/utils/sourcemaps.rs:276]: AFAICT the returned reference is never used.

Comment (szokeasaurusrex) [reply src/utils/sourcemaps.rs:276]: okay, I figured it out. I thought I would have to add the sourcemap (new parameter to `unpack_ram_bundle`) into the sourcemap processor, but I later realized that is unnecessary, since we anyways were overwriting its entry in the processor on line 478 by inserting at the same key

Comment (szokeasaurusrex) [reply src/utils/sourcemaps.rs:276]: so I will remove the returned reference

**Review by szokeasaurusrex — COMMENTED** [review]
Nice catch on the review btw!

**Review by loewenheim — APPROVED** [review]
