### PR TITLE
fix(releases): Serialize project IDs as integers

### LINKED ISSUE #3066: Send project IDs as integers for release endpoints
Self hosted versions (besides the most recent ones) only can take project IDs at the release endpoints when they are serialized as JSON integers, not as strings, as they are affected by [a bug](https://github.com/getsentry/sentry/issues/105038) which was only fixed in getsentry/sentry#105159.

Although SaaS and new self-hosted versions will now accept project IDs when serialized as strings, we should serialize them as integers, instead, to ensure compatibility with older self-hosted versions.

### PR DESCRIPTION
**Pull request by szokeasaurusrex**
### Description
Serialize project IDs as integers when creating a new release. This restores compatibility with self-hosted Sentry versions which lack [this bug fix](https://linear.app/getsentry/review/fixapi-accept-project-ids-as-strings-in-organization-releases-endpoint-0c24c083a8ac) to properly handle project IDs serialized as strings.

### Issues
- Resolves #3066
- Resolves [CLI-261](https://linear.app/getsentry/issue/CLI-261/send-project-ids-as-integers-for-release-endpoints)
- See also https://github.com/getsentry/sentry/issues/105038

### CODE REVIEW

File: src/api/serialization.rs [hunk 1]
```diff
@@ -0,0 +1,128 @@
...
+        ///
+        /// Project IDs always contain only digits.
+        static PROJECT_ID_REGEX: LazyLock<Regex> =
+            LazyLock::new(|| Regex::new(r"^\d+$").expect("regex is valid"));
+
+        let value = value.as_ref();
+
+        PROJECT_ID_REGEX
+            .is_match(value)
+            .then(|| value.parse().ok().map(IdSlug::Id))
```
Comment (lcian) [inline src/api/serialization.rs:58]: nit: probably you can just attempt to `parse` it without applying the regex. If the parsing fails, you can fall back to considering it a slug.

Comment (szokeasaurusrex) [reply src/api/serialization.rs:58]: I tried this in a previous iteration, but it fails for some edge cases. For example, negative numbers parse correctly (even though IDs cannot be negative, despite the fact that the database table apparently stores them as signed integers). Even checking that the values are greater than or equal to zero does not work, because "-0" (which can be a valid project slug) parses to 0.

Comment (szokeasaurusrex) [reply src/api/serialization.rs:58]: I think the regex is the most reliable here
