### PR TITLE
fix: Also disable SSL peer certificate verification with flag

### LINKED ISSUE #178: unable to get sentry-cli to disable verify_ssl
No matter how hard I try, it seems that the `verify_ssl=false` is not working on `~/.sentryclirc`

```
SPIS-TECH-MB84:~ pmlg673f$ cat .sentryclirc 
[defaults]
project=fjord-ios
org=sentry
url=https://sentry.apps.vpcf-prod.in.spdigital.io/

[http]
verify_ssl=false
check_ssl_revoke=false

[log]
level=DEBUG

[auth]
token=853e361b968b454c8d31f5ea357a1282efc1f787beae465c9e3529d994c1f4d7
SPIS-TECH-MB84:~ pmlg673f$ sentry-cli info
[INFO] sentry_cli::api request GET https://sentry.apps.vpcf-prod.in.spdigital.io/api/0/
[INFO] sentry_cli::api using token authentication
Sentry Server: https://sentry.apps.vpcf-prod.in.spdigital.io/
Default Organization: sentry
Default Project: fjord-ios

Authentication Info:
  Method: Auth Token
  (failure on authentication: http error: [60] Peer certificate cannot be authenticated with given CA certificates (SSL certificate problem: unable to get local issuer certificate))
SPIS-TECH-MB84:~ pmlg673f$ openssl version -a
OpenSSL 1.0.2n  7 Dec 2017
built on: reproducible build, date unspecified
platform: darwin64-x86_64-cc
options:  bn(64,64) rc4(ptr,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: clang -I. -I.. -I../include  -fPIC -fno-common -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -arch x86_64 -O3 -DL_ENDIAN -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/usr/local/etc/openssl"
```

It also come to my attention that `verify_ssl` code is set to true no matter the circumstances. Please look into it and fix it. Thanks 🙏

https://github.com/getsentry/sentry-cli/blob/e66a69e4604b5796c4fd39ae01860624b4bb82d6/src/config.rs#L185-L191

### PR DESCRIPTION
**Pull request by jan-auer**
The configuration option `http.verify_ssl` should disable verification of the SSL certificate. Right now, it only disables host name verification ([`CURLOPT_SSL_VERIFYHOST`](https://curl.haxx.se/libcurl/c/CURLOPT_SSL_VERIFYHOST.html)) but it should also/instead disable certificate verification ([`CURLOPT_SSL_VERIFYPEER`](https://curl.haxx.se/libcurl/c/CURLOPT_SSL_VERIFYPEER.html)).

I'd argue that we should **only** disable peer certificate validation and leave host validation in place to support self-signed certificates.

Fixes #178

### CODE REVIEW

File: src/api.rs [hunk 1]
```diff
@@ -174,6 +174,7 @@ impl<'a> Api<'a> {
             handle.proxy_password(proxy_password)?;
         }
         handle.ssl_verify_host(self.config.should_verify_ssl())?;
```
Comment (jan-auer) [inline src/api.rs]: @mitsuhiko what do you think, remove this line?
