### PR TITLE
fix: warn about missing SENTRY_RELEASE when it's set to empty string

### LINKED ISSUE #2385: Sentry reported an error: '' does not match '^[^/]+$' (http status: 400)
### CLI Version

2.41.1

### Operating System and Architecture

- [ ] macOS (arm64)
- [ ] macOS (x86_64)
- [ ] Linux (i686)
- [x] Linux (x86_64)
- [ ] Linux (armv7)
- [ ] Linux (aarch64)
- [ ] Windows (i686)
- [ ] Windows (x86_64)

### Operating System Version

Ubuntu 24.04.1 LTS

### Link to reproduction repository

_No response_

### CLI Command

sentry-cli sourcemaps upload --org bysolutions --project pi ../public/build

### Exact Reproduction Steps

1. npx @sentry/wizard@latest -i sourcemaps
2. gulp all --production
3. npm run sentry:sourcemaps (That execute => sentry-cli sourcemaps inject --org bysolutions --project pi ../public/build && sentry-cli sourcemaps upload --org bysolutions --project pi ../public/build)

### Expected Results

I expect process work with success message

### Actual Results

> web@1.0.0 sentry:sourcemaps
> sentry-cli sourcemaps inject --org bysolutions --project pi ../public/build && sentry-cli sourcemaps upload --org bysolutions --project pi ../public/build

> Searching ../public/build
> Found 49 files
> Analyzing 49 sources
> Analyzing completed in 0.003s
> Injecting debug ids

Source Map Debug ID Injection Report
  Ignored: The following source files already have debug ids
    af8b11b1-adea-5eb3-8279-05721104444b - ../public/build/js/test-7e83d29765.js
    f4e4ad41-3e79-5e6d-848a-159a46b66a90 - ../public/build/js/test.js
.....

> Found 49 files
> Analyzing 49 sources
> Analyzing completed in 0.005s
> Rewriting sources
> Rewriting completed in 0s
> Adding source map references
> Bundling completed in 1.764s
> Bundled 49 files for upload
> Bundle ID: eb7845c5-0c25-51c6-8b2d-e00bb7d8df80
> Optimizing completed in 0.032s
error: API request failed

Caused by:
    sentry reported an error: '' does not match '^[^/]+$' (http status: 400)

### Logs

```
......

> Found 49 files
> Analyzing 49 sources
> Analyzing completed in 0.005s
> Rewriting sources
> Rewriting completed in 0s
> Adding source map references
  DEBUG   2025-02-14 13:34:41.696971286 +01:00 request GET https://sentry.io/api/0/projects/bysolutions/pi/releases//files/?cursor=&checksum=0272d4ef07d4770175de4f05db68e62fc1cde392&checksum=153224266a22cf704a497fe440018d38d8528e32&checksum=1e9fa4d280114582acb50c3dfe2014bf6359afb4&checksum=25078ef63b0919369620f8473dac4b0b69724400&checksum=276595eb07290cdcbaff8ac14c90e9b991966fcb&checksum=27a4e6c5019c5ecc15e12817547ef5eedbdc69b3&checksum=28f622fba60155fe58ea8fb264693cf784f8712e&checksum=3d667afb715300396c956116b91d58fcc631a604&checksum=4314511d9ae088a9984024c293c4084ae2430711&checksum=43d3c438a3f7143aaa1695116e7b617ea8446033&checksum=57831709b1b0903ab410b781196aa615a8384af9&checksum=617ed325ae9f77c193f4b44e2bdcd3a19e88a2de&checksum=6a14fe0f7cc9ce6d7191fa64544c22264b054d6f&checksum=6e205556aef7eee5695c500bf504f435e8e6f72a&checksum=6f2b1bf439dd8b0602b7e1d67357727a3811696b&checksum=72151e76a17c4fedf8f28c8994baed18efac0591&checksum=72b4cc5b105ffb21d8eb90b730769df8fe419916&checksum=72bf149c6e91e481a540a4c8edcd8f0dc4bc1e47&checksum=7e7260ea29a61f9625ae0c1a681778d1460a6d99&checksum=8a7bafeed69073357102463ce63e187aec1a0705&checksum=93359185817673a535350047066b91f62b93c74a&checksum=969cd2d0f49aa2832f632141e93fc6acd573e016&checksum=9b4412f522b4a08c30b481cb71b17039000595f2&checksum=9ca79601733921a9f92b3a9fe9dadb4dcec6139f&checksum=a741171d63dbd7ba297cfa822b59bc7285e143e0&checksum=a9bb57b2f465e67f4427f6cad3df0977da42c9b8&checksum=ab3389bae710128555a8f2d0031e0e136ad61306&checksum=b7d4c7fb8fb022ab8adf35bbf243af881a08cfe8&checksum=b8562ac9ff2ca20bec65e29e3480e1e2d757005d&checksum=bbaf27d00cddca37d72eedaf200a5db8d06ac24e&checksum=bfb1a8888b0b04b06d15e47341f6c8e5200e41f7&checksum=c08f41af217ca0aae3e42eed831b064fd344cdf6&checksum=c4d594d42ffc56ebfa52042becf9ca60358985e9&checksum=c64c0ab137b6ed56890db4f824a97524ee734d46&checksum=c6e2909e999b48b00438f54dc0525541f9d020ef&checksum=c84732441815b69b244fb42268d935f2cd724100&checksum=ca25a8f243cece6007dac16c4a07d3bb1b164242&checksum=ce254605cf989e83f34f2243f45f08d50d7f0842&checksum=cf901ddd8b279db6eb8209916fa3d97f41760488&checksum=cf901ddd8b279db6eb8209916fa3d97f41760488&checksum=cf901ddd8b279db6eb8209916fa3d97f41760488&checksum=d630333e8cacd4e8e29c1010b5dc90d649ef2f19&checksum=dd745f5da43653ae3ef207bc3d0fb0d04bdef631&checksum=de7c311cadc5af40983f735f7b26c13f15c1a95f&checksum=de7c311cadc5af40983f735f7b26c13f15c1a95f&checksum=de7c311cadc5af40983f735f7b26c13f15c1a95f&checksum=e1f13c7c9ab30287ffc30c017bc5345b88585bb6&checksum=e215016bc22569004f83156ca73ed29839d49b85&checksum=eaf8eb43ae41af35348087feb99bd8736b74e50a
  DEBUG   2025-02-14 13:34:41.697025318 +01:00 using token authentication
  DEBUG   2025-02-14 13:34:41.697030868 +01:00 retry number 0, max retries: 0
  DEBUG   2025-02-14 13:34:41.697220495 +01:00 > GET /api/0/projects/bysolutions/pi/releases//files/?cursor=&checksum=0272d4ef07d4770175de4f05db68e62fc1cde392&checksum=153224266a22cf704a497fe440018d38d8528e32&checksum=1e9fa4d280114582acb50c3dfe2014bf6359afb4&checksum=25078ef63b0919369620f8473dac4b0b69724400&checksum=276595eb07290cdcbaff8ac14c90e9b991966fcb&checksum=27a4e6c5019c5ecc15e12817547ef5eedbdc69b3&checksum=28f622fba60155fe58ea8fb264693cf784f8712e&checksum=3d667afb715300396c956116b91d58fcc631a604&checksum=4314511d9ae088a9984024c293c4084ae2430711&checksum=43d3c438a3f7143aaa1695116e7b617ea8446033&checksum=57831709b1b0903ab410b781196aa615a8384af9&checksum=617ed325ae9f77c193f4b44e2bdcd3a19e88a2de&checksum=6a14fe0f7cc9ce6d7191fa64544c22264b054d6f&checksum=6e205556aef7eee5695c500bf504f435e8e6f72a&checksum=6f2b1bf439dd8b0602b7e1d67357727a3811696b&checksum=72151e76a17c4fedf8f28c8994baed18efac0591&checksum=72b4cc5b105ffb21d8eb90b730769df8fe419916&checksum=72bf149c6e91e481a540a4c8edcd8f0dc4bc1e47&checksum=7e7260ea29a61f9625ae0c1a681778d1460a6d99&checksum=8a7bafeed69073357102463ce63e187aec1a0705&checksum=93359185817673a535350047066b91f62b93c74a&checksum=969cd2d0f49aa2832f632141e93fc6acd573e016&checksum=9b4412f522b4a08c30b481cb71b17039000595f2&checksum=9ca79601733921a9f92b3a9fe9dadb4dcec6139f&checksum=a741171d63dbd7ba297cfa822b59bc7285e143e0&checksum=a9bb57b2f465e67f4427f6cad3df0977da42c9b8&checksum=ab3389bae710128555a8f2d0031e0e136ad61306&checksum=b7d4c7fb8fb022ab8adf35bbf243af881a08cfe8&checksum=b8562ac9ff2ca20bec65e29e3480e1e2d757005d&checksum=bbaf27d00cddca37d72eedaf200a5db8d06ac24e&checksum=bfb1a8888b0b04b06d15e47341f6c8e5200e41f7&checksum=c08f41af217ca0aae3e42eed831b064fd344cdf6&checksum=c4d594d42ffc56ebfa52042becf9ca60358985e9&checksum=c64c0ab137b6ed56890db4f824a97524ee734d46&checksum=c6e2909e999b48b00438f54dc0525541f9d020ef&checksum=c84732441815b69b244fb42268d935f2cd724100&checksum=ca25a8f243cece6007dac16c4a07d3bb1b164242&checksum=ce254605cf989e83f34f2243f45f08d50d7f0842&checksum=cf901ddd8b279db6eb8209916fa3d97f41760488&checksum=cf901ddd8b279db6eb8209916fa3d97f41760488&checksum=cf901ddd8b279db6eb8209916fa3d97f41760488&checksum=d630333e8cacd4e8e29c1010b5dc90d649ef2f19&checksum=dd745f5da43653ae3ef207bc3d0fb0d04bdef631&checksum=de7c311cadc5af40983f735f7b26c13f15c1a95f&checksum=de7c311cadc5af40983f735f7b26c13f15c1a95f&checksum=de7c311cadc5af40983f735f7b26c13f15c1a95f&checksum=e1f13c7c9ab30287ffc30c017bc5345b88585bb6&checksum=e215016bc22569004f83156ca73ed29839d49b85&checksum=eaf8eb43ae41af35348087feb99bd8736b74e50a HTTP/1.1
  DEBUG   2025-02-14 13:34:41.697233650 +01:00 > Host: sentry.io
  DEBUG   2025-02-14 13:34:41.697238429 +01:00 > Accept: */*
  DEBUG   2025-02-14 13:34:41.697242156 +01:00 > Connection: TE
  DEBUG   2025-02-14 13:34:41.697245122 +01:00 > TE: gzip
  DEBUG   2025-02-14 13:34:41.697248909 +01:00 > User-Agent: sentry-cli/2.41.1
  DEBUG   2025-02-14 13:34:41.697266071 +01:00 > Authorization: Bearer sntrys_e***
  DEBUG   2025-02-14 13:34:41.964915375 +01:00 < HTTP/1.1 404 Not Found
  DEBUG   2025-02-14 13:34:41.964939551 +01:00 < server: nginx
  DEBUG   2025-02-14 13:34:41.964947987 +01:00 < date: Fri, 14 Feb 2025 12:34:41 GMT
  DEBUG   2025-02-14 13:34:41.964955641 +01:00 < content-type: application/json
  DEBUG   2025-02-14 13:34:41.964962624 +01:00 < vary: Accept-Encoding,Accept-Language, Cookie
  DEBUG   2025-02-14 13:34:41.964969928 +01:00 < allow: GET, PUT, DELETE, HEAD, OPTIONS
  DEBUG   2025-02-14 13:34:41.964974918 +01:00 < access-control-allow-methods: GET, PUT, DELETE, HEAD, OPTIONS
  DEBUG   2025-02-14 13:34:41.964984395 +01:00 < access-control-allow-headers: X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization, Content-Encoding, sentry-trace, baggage, X-CSRFToken
  DEBUG   2025-02-14 13:34:41.964991138 +01:00 < access-control-expose-headers: X-Sentry-Error, X-Sentry-Direct-Hit, X-Hits, X-Max-Hits, Endpoint, Retry-After, Link
  DEBUG   2025-02-14 13:34:41.964999203 +01:00 < access-control-allow-origin: *
  DEBUG   2025-02-14 13:34:41.965006096 +01:00 < x-sentry-rate-limit-remaining: 39
  DEBUG   2025-02-14 13:34:41.965014803 +01:00 < x-sentry-rate-limit-limit: 40
  DEBUG   2025-02-14 13:34:41.965022147 +01:00 < x-sentry-rate-limit-reset: 1739536482
  DEBUG   2025-02-14 13:34:41.965028909 +01:00 < x-sentry-rate-limit-concurrentremaining: 24
  DEBUG   2025-02-14 13:34:41.965053055 +01:00 < x-sentry-rate-limit-concurrentlimit: 25
  DEBUG   2025-02-14 13:34:41.965060258 +01:00 < content-language: en
  DEBUG   2025-02-14 13:34:41.965067011 +01:00 < x-frame-options: deny
  DEBUG   2025-02-14 13:34:41.965075457 +01:00 < x-content-type-options: nosniff
  DEBUG   2025-02-14 13:34:41.965082630 +01:00 < x-xss-protection: 1; mode=block
  DEBUG   2025-02-14 13:34:41.965103860 +01:00 < content-security-policy: media-src *; base-uri 'none'; img-src * blob: data:; font-src * data:; object-src 'none'; script-src 'self' 'unsafe-inline' 'report-sample' s1.sentry-cdn.com js.sentry-cdn.com browser.sentry-cdn.com statuspage-production.s3.amazonaws.com static.zdassets.com aui-cdn.atlassian.com connect-cdn.atl-paas.net js.stripe.com 'strict-dynamic' cdn.pendo.io data.pendo.io pendo-io-static.storage.googleapis.com pendo-static-5634074999128064.storage.googleapis.com; connect-src 'self' *.algolia.net *.algolianet.com *.algolia.io sentry.io *.sentry.io s1.sentry-cdn.com o1.ingest.sentry.io api2.amplitude.com app.pendo.io data.pendo.io reload.getsentry.net t687h3m0nh65.statuspage.io sentry.zendesk.com ekr.zdassets.com maps.googleapis.com; frame-src app.pendo.io demo.arcade.software js.stripe.com sentry.io; default-src 'none'; style-src * 'unsafe-inline'; frame-ancestors 'self' *.sentry.io; worker-src blob:; report-uri https://o1.ingest.sentry.io/api/54785/security/?sentry_key=f724a8a027db45f5b21507e7142ff78e&sentry_release=3c9463e178855c1ee7f837e3ccf2e7262a84b5de
  DEBUG   2025-02-14 13:34:41.965119099 +01:00 < x-envoy-upstream-service-time: 90
  DEBUG   2025-02-14 13:34:41.965126794 +01:00 < x-sentry-proxy-url: http://10.2.0.67:8999/api/0/projects/bysolutions/pi/releases/files/
  DEBUG   2025-02-14 13:34:41.965134729 +01:00 < x-envoy-attempt-count: 1
  DEBUG   2025-02-14 13:34:41.965141291 +01:00 < x-served-by: getsentry-control-web-default-common-production-55b444f7cf4x7pd
  DEBUG   2025-02-14 13:34:41.965148284 +01:00 < x-served-by: frontend-default-66b79b5797-7hqlj
  DEBUG   2025-02-14 13:34:41.965156019 +01:00 < strict-transport-security: max-age=31536000; includeSubDomains; preload
  DEBUG   2025-02-14 13:34:41.965163082 +01:00 < via: 1.1 google
  DEBUG   2025-02-14 13:34:41.965193359 +01:00 < Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
  DEBUG   2025-02-14 13:34:41.965210311 +01:00 < Transfer-Encoding: chunked
  DEBUG   2025-02-14 13:34:41.966151704 +01:00 response status: 404
> Bundling completed in 1.799s
> Bundled 49 files for upload
> Bundle ID: eb7845c5-0c25-51c6-8b2d-e00bb7d8df80
> Optimizing completed in 0.033s
  DEBUG   2025-02-14 13:34:43.799192914 +01:00 request POST https://sentry.io/api/0/organizations/bysolutions/artifactbundle/assemble/
  DEBUG   2025-02-14 13:34:43.799205979 +01:00 using token authentication
  DEBUG   2025-02-14 13:34:43.799215236 +01:00 json body: {"checksum":"ce6bf2717e3cb22350ce4ae8f3ba5dcf02107c91","chunks":["0f42f0e5a8ba33533a5f5b06607a7fba67e8b91e","84a766c381c8cf5b0a77cec10c3292ac2ca10f9d"],"projects":["pi"],"version":""}
  DEBUG   2025-02-14 13:34:43.799220977 +01:00 retry number 0, max retries: 5
  DEBUG   2025-02-14 13:34:43.799344700 +01:00 > POST /api/0/organizations/bysolutions/artifactbundle/assemble/ HTTP/1.1
  DEBUG   2025-02-14 13:34:43.799350331 +01:00 > Host: sentry.io
  DEBUG   2025-02-14 13:34:43.799354469 +01:00 > Accept: */*
  DEBUG   2025-02-14 13:34:43.799359097 +01:00 > Connection: TE
  DEBUG   2025-02-14 13:34:43.799364057 +01:00 > TE: gzip
  DEBUG   2025-02-14 13:34:43.799369868 +01:00 > User-Agent: sentry-cli/2.41.1
  DEBUG   2025-02-14 13:34:43.799388853 +01:00 > Authorization: Bearer sntrys_e***
  DEBUG   2025-02-14 13:34:43.799393182 +01:00 > Content-Type: application/json
  DEBUG   2025-02-14 13:34:43.799417137 +01:00 > Content-Length: 183
  DEBUG   2025-02-14 13:34:44.031688216 +01:00 < HTTP/1.1 400 Bad Request
  DEBUG   2025-02-14 13:34:44.031712882 +01:00 < server: nginx
  DEBUG   2025-02-14 13:34:44.031719545 +01:00 < date: Fri, 14 Feb 2025 12:34:44 GMT
  DEBUG   2025-02-14 13:34:44.031725556 +01:00 < content-type: application/json
  DEBUG   2025-02-14 13:34:44.031730676 +01:00 < allow: POST, OPTIONS
  DEBUG   2025-02-14 13:34:44.031735996 +01:00 < access-control-allow-methods: POST, OPTIONS
  DEBUG   2025-02-14 13:34:44.031744592 +01:00 < access-control-allow-headers: X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization, Content-Encoding, sentry-trace, baggage, X-CSRFToken
  DEBUG   2025-02-14 13:34:44.031751155 +01:00 < access-control-expose-headers: X-Sentry-Error, X-Sentry-Direct-Hit, X-Hits, X-Max-Hits, Endpoint, Retry-After, Link
  DEBUG   2025-02-14 13:34:44.031757607 +01:00 < access-control-allow-origin: *
  DEBUG   2025-02-14 13:34:44.031763007 +01:00 < x-sentry-rate-limit-remaining: 39
  DEBUG   2025-02-14 13:34:44.031768778 +01:00 < x-sentry-rate-limit-limit: 40
  DEBUG   2025-02-14 13:34:44.031775731 +01:00 < x-sentry-rate-limit-reset: 1739536485
  DEBUG   2025-02-14 13:34:44.031781732 +01:00 < x-sentry-rate-limit-concurrentremaining: 24
  DEBUG   2025-02-14 13:34:44.031787513 +01:00 < x-sentry-rate-limit-concurrentlimit: 25
  DEBUG   2025-02-14 13:34:44.031793374 +01:00 < vary: Accept-Language, Cookie
  DEBUG   2025-02-14 13:34:44.031799576 +01:00 < content-language: en
  DEBUG   2025-02-14 13:34:44.031807911 +01:00 < x-frame-options: deny
  DEBUG   2025-02-14 13:34:44.031814784 +01:00 < x-content-type-options: nosniff
  DEBUG   2025-02-14 13:34:44.031821277 +01:00 < x-xss-protection: 1; mode=block
  DEBUG   2025-02-14 13:34:44.031828230 +01:00 < content-security-policy: style-src * 'unsafe-inline'; default-src 'none'; media-src *; object-src 'none'; worker-src blob:; frame-ancestors 'self' *.sentry.io; connect-src 'self' *.algolia.net *.algolianet.com *.algolia.io sentry.io *.sentry.io s1.sentry-cdn.com o1.ingest.sentry.io api2.amplitude.com app.pendo.io data.pendo.io reload.getsentry.net t687h3m0nh65.statuspage.io sentry.zendesk.com ekr.zdassets.com maps.googleapis.com; frame-src app.pendo.io demo.arcade.software js.stripe.com sentry.io; font-src * data:; script-src 'self' 'unsafe-inline' 'report-sample' s1.sentry-cdn.com js.sentry-cdn.com browser.sentry-cdn.com statuspage-production.s3.amazonaws.com static.zdassets.com aui-cdn.atlassian.com connect-cdn.atl-paas.net js.stripe.com 'strict-dynamic' cdn.pendo.io data.pendo.io pendo-io-static.storage.googleapis.com pendo-static-5634074999128064.storage.googleapis.com; img-src * blob: data:; base-uri 'none'; report-uri https://o1.ingest.sentry.io/api/54785/security/?sentry_key=f724a8a027db45f5b21507e7142ff78e&sentry_release=3c9463e178855c1ee7f837e3ccf2e7262a84b5de
  DEBUG   2025-02-14 13:34:44.031858988 +01:00 < x-envoy-upstream-service-time: 55
  DEBUG   2025-02-14 13:34:44.031865981 +01:00 < x-sentry-proxy-url: http://10.2.0.67:8999/api/0/organizations/bysolutions/artifactbundle/assemble/
  DEBUG   2025-02-14 13:34:44.031874317 +01:00 < x-envoy-attempt-count: 1
  DEBUG   2025-02-14 13:34:44.031880628 +01:00 < x-served-by: getsentry-control-web-default-common-production-55b444f7cfbmb8d
  DEBUG   2025-02-14 13:34:44.031888253 +01:00 < x-served-by: frontend-default-66b79b5797-wph97
  DEBUG   2025-02-14 13:34:44.031895436 +01:00 < strict-transport-security: max-age=31536000; includeSubDomains; preload
  DEBUG   2025-02-14 13:34:44.031902159 +01:00 < via: 1.1 google
  DEBUG   2025-02-14 13:34:44.031908621 +01:00 < Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
  DEBUG   2025-02-14 13:34:44.031915965 +01:00 < Transfer-Encoding: chunked
  DEBUG   2025-02-14 13:34:44.031996807 +01:00 response status: 400
  DEBUG   2025-02-14 13:34:44.032012507 +01:00 body: {"error":"'' does not match '^[^/]+$'"}
error: API request failed

Caused by:
    sentry reported an error: '' does not match '^[^/]+$' (http status: 400)
```

### PR DESCRIPTION
**Pull request by a-hariti**
I'm not sure if this covers all instances/paths

closes #2385

### CODE REVIEW

**Comment by a-hariti** [comment]
Yes, I would love to

File: src/config.rs [hunk 1]
```diff
@@ -363,8 +363,12 @@ impl Config {
         matches
             .get_one::<String>("release")
```
Comment (a-hariti) [inline src/config.rs:364]: this is trying to read `SENTRY_RELEASE` only after if tails to find a `release` in the clap match object right?

**Comment by a-hariti** [comment]
is on this line? https://github.com/getsentry/sentry-cli/blob/master/src/utils/file_upload.rs#L99
 @szokeasaurusrex

File: src/config.rs [hunk 2]
```diff
@@ -363,8 +363,12 @@ impl Config {
...
             .cloned()
-            .or_else(|| env::var("SENTRY_RELEASE").ok())
-            .ok_or_else(|| format_err!("A release slug is required (provide with --release)"))
+            .or_else(|| {
+                env::var("SENTRY_RELEASE")
+                    .ok()
+                    .and_then(|v| if v.is_empty() { None } else { Some(v) })
```
Comment (szokeasaurusrex) [inline src/config.rs:369]:
```suggestion
                    .filter(|v| !v.is_empty())
```

You should use [`Option::filter`](https://doc.rust-lang.org/std/option/enum.Option.html#method.filter) here.

File: src/utils/file_upload.rs [hunk 3]
```diff
@@ -96,7 +96,7 @@ pub struct UploadContext<'a> {
 impl UploadContext<'_> {
     pub fn release(&self) -> Result<&str> {
         self.release
-            .ok_or_else(|| anyhow!("A release slug is required (provide with --release)"))
+            .ok_or_else(|| anyhow!("A release slug is required (provide with --release) or set the SENTRY_RELEASE environment variable"))
```
Comment (szokeasaurusrex) [inline src/utils/file_upload.rs:99]:
```suggestion
            .ok_or_else(|| anyhow!("A release slug is required (provide with --release or by setting the SENTRY_RELEASE environment variable)"))
```

**Review by szokeasaurusrex — COMMENTED** [review]
Looks good, nice first PR! I noticed a couple small things to change before we merge, but I'll approve once those are addressed

**Review by szokeasaurusrex — APPROVED** [review]
Nice!
