### PR TITLE
fix: Add support for --url-prefix=app:///

### LINKED ISSUE #311: sentry-cli strips out "//" from --url-prefix "app://"
Hi,

I'm using ionic for my mobile app.
I can get bugs reported to sentry.
I can get sourcemap uploaded.
But the exception stack doesn’t link with sourcemaps.

I suspect it's to do with the urls used in exception stack. 
```
app:///vendor.js in viewWrappedDebugError at line 9857:15
app:///vendor.js in callWithDebugContext at line 15103:15
app:///vendor.js in Object.debugHandleEvent [as handleEvent] at line 14680:12
app:///vendor.js in dispatchEvent at line 10057:25
app:///vendor.js at line 10671:38
app:///vendor.js in HTMLButtonElement.<anonymous> at line 40187:53
app:///polyfills.js in t.invokeTask at line 3:15660
app:///vendor.js in Object.onInvokeTask at line 4973:33
app:///polyfills.js in t.invokeTask at line 3:15581
app:///polyfills.js in r.runTask at line 3:10834
app:///polyfills.js in e.invokeTask [as invoke] at line 3:16794
app:///polyfills.js in p at line 2:27648
app:///polyfills.js in HTMLButtonElement.v at line 2:27893
```

So, suspecting it's to do with the sourcemap url, I tried to set --url-prefix with "app://", but sentry-cli strips out the "//". 
```
.\node_modules\.bin\sentry-cli releases files 0.0.1 upload-sourcemaps --url-prefix 'app://'
 .\.sourcemaps\ .\www\build\
> Analyzing 8 sources
> Adding source map references
> Uploading source maps for release 0.0.1
> app:/vendor.js.map
```

Has anyone came across this before?

### PR DESCRIPTION
**Pull request by mitsuhiko**
Fixes #311

I wanted to add tests for this but this requires a greater refactoring as this is currently not well
abstracted :(

### CODE REVIEW

File: src/commands/releases.rs [hunk 1]
```diff
@@ -698,10 +698,14 @@ fn execute_files_upload<'a>(
...
 fn get_url_prefix_from_args<'a, 'b>(matches: &'b ArgMatches<'a>) -> &'b str {
-    matches
+    let mut rv = matches
         .value_of("url_prefix")
-        .unwrap_or("~")
-        .trim_end_matches('/')
+        .unwrap_or("~");
+    // remove a single slash from the end.  so ~/ becomes ~ and app:/// becomes app://
+    if rv.ends_with('/') {
+        rv = &rv[..rv.len() - 1];
```
Comment (HazAT) [inline src/commands/releases.rs]: Can we at least something add like:
`info!("Removed trailing slash from url-prefix")`
to have more insight for the user?

Comment (mitsuhiko) [reply src/commands/releases.rs]: The trailing slash will always be removed though. We never documented `~` to be a valid prefix, we always told people to supply `~/`. So the removing is the default case. It's only thrown away because some code later adds it.

Comment (josh-m-sharpe) [reply src/commands/releases.rs]: I don't think this is the correct fix for https://github.com/getsentry/sentry-cli/issues/311

There shouldn't be any stripping.

My usecase requires that the prefix be `app:///` - I think OP requires it to be `app://`

Why should we have to add a slash to what we need only to have it removed?

Comment (jan-auer) [reply src/commands/releases.rs]: @josh-m-sharpe At least in the example it seems that the stack trace contains `app:///`, so this should be fine
