### PR TITLE
Sourcemap upload strict mode

### LINKED ISSUE #1705: Uploadling source maps fails silently, if none are found
### Environment

Hi there, we are using sentry-cli to upload source map files from a github runner.
We changed our output dir of our project recently and didn't correct that path in the sentry-cli upload command.
Unfortunately the cli does not report this as an error, so we discovered some missing source maps later own wondering why some are there and some are not.

### Steps to Reproduce

Pass a wrong path to sentry-cli to upload source map files.
E.g.:

`sentry-cli releases files $BUILD_VERSION upload-sourcemaps /tmp/foo'`

### Expected/Actual Result

sentry-cli should throw an error / break the build in case the upload command does not do anything.
At least a strict mode (as per toggle, e.g. --strict) would be appreciated.

### Logs

Failed attempt log output

```
2023-07-31T09:45:14.1015340Z $ sentry-cli releases files $BUILD_VERSION upload-sourcemaps build/webpack/static/foo/dist --rewrite --url-prefix '~/foo/dist'
2023-07-31T09:45:14.1015956Z > Rewriting sources
2023-07-31T09:45:14.1016458Z > Adding source map references
2023-07-31T09:45:14.1017127Z > Nothing to upload
2023-07-31T09:45:14.1017384Z Done in 0.35s.
```

vs fixed path (note the ../):

```
2023-07-31T09:53:11.5534360Z $ sentry-cli releases files $BUILD_VERSION upload-sourcemaps ../build/webpack/static/foo/dist --rewrite --url-prefix '~/foo/dist'
2023-07-31T09:53:11.5534936Z > Found 17 files
2023-07-31T09:53:11.5535231Z > Analyzing 17 sources
2023-07-31T09:53:11.5535543Z > Rewriting sources
2023-07-31T09:53:11.5535898Z > Adding source map references
2023-07-31T09:53:11.5536242Z > Bundled 17 files for upload
2023-07-31T09:53:11.5536683Z > Bundle ID: 68c59ed6-1603-59a0-b3d4-e2f6384d8cf8
2023-07-31T09:53:11.6532171Z > Uploaded files to Sentry
2023-07-31T09:53:11.7532153Z > File upload complete (processing pending on server)
```

Probably related to #1645 ?

### PR DESCRIPTION
**Pull request by szokeasaurusrex**
Closes #1705

### CODE REVIEW

File: src/utils/sourcemaps.rs [hunk 1]
```diff
@@ -852,7 +853,19 @@ impl SourceMapProcessor {
...
-        Ok(())
+        Ok(files_needing_upload)
+    }
+
+    /// Upload all files in "strict" mode. Strict mode differs from a normal upload
+    /// only when there are no files to upload. In strict mode, having no files to
+    /// upload results in an error, whereas such an upload is successful in normal
+    /// (non-strict) mode. On success, the number of uploaded files is returned in
+    /// an Ok()
+    pub fn upload_strict(&mut self, context: &UploadContext<'_>) -> Result<usize> {
```
Comment (szokeasaurusrex) [inline src/utils/sourcemaps.rs:864]: I implemented this change by creating a separate function for strict uploads. The other options I considered were adding a field to the `UploadContext` struct or an argument to the `upload` function which would store a boolean representing whether strict mode is enabled. However, since we call the `upload` function and use the `UploadContext` struct in multiple places, we would need to change all of these uses to go with either or those options.

Comment (loewenheim) [reply src/utils/sourcemaps.rs:864]: I think it makes perfect sense to add a separate function for this.

**Review by loewenheim — APPROVED** [review]

**Comment by hennr** [comment]
Thanks folks!

Should this be mentioned in the docs somewhere as well?

**Comment by szokeasaurusrex** [comment]
> Should this be mentioned in the docs somewhere as well?

Good catch! Yes, we will be sure to add this feature to the docs.
